apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-chat-web-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat-web-app
  template:
    metadata:
      labels:
        app: chat-web-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3005
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
