apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat-web-app
  template:
    metadata:
      labels:
        app: chat-web-app
    spec:
      initContainers:
        - name: check-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z chat-web-app-redis-master 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3005
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-web-app-redis
                  key: redis-password
