replicaCount: 2

image:
  repository: ariffazman/chat-web-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3005

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

redis:
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false